version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python -m virtualenv venv  
            source venv/bin/activate
            pip3 install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            coverage run --source='.' manage.py test
            coverage report
            

      # - run:
      #     name: Running pytest
      #     command: |
      #       . venv/bin/activate
            
      #       coverage run --source='.' -m pytest
      #       coverage report
      #       coverage html  # open htmlcov/index.html in a browser
            

      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = NYARAS" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
      - run:
         name: create packages
         command: |
           python3 setup.py sdist

      - run:
         name: upload to pypi
         command: |
           . venv/bin/activate
           twine upload dist/*
            
      - store_artifacts:
          path: test-reports
          destination: python_app
